# CONFIG FILE SIMPLE-RENAME
# THIS CONFIG FILE WAS CREATED BY SIMPLE-RENAME (v8.5)
#Language (en , es, eu, nl, fr, custom)
Language: en
#METRICS: Enable or Disable Metrics
Metrics: true
#UPDATER: Enable or Disable the update notifier
Updater: true
#ECONOMY:(If you set it to "true" yo need to have Vault installed)
Economy: false
#PRICES: Price to rename and relore items 
Prices:
  Nprice: 10 
  Lprice: 10
  BookPrice: 10
  ClearPrice: 10
  PastePrice: 10
XPprices:
  Enable: false
  NameXP: 5
  LoreXP: 5
  BookXP: 5
  ClearXP: 5
  PasteXP: 5
#Blacklisted words
BlackList:
  - blaclistedwords
#Blaclisted items / blocks. Use names, NOT IDs 
BlackListID:
  - air
#Max characters
CharacterLimit: 0
Prefix: '[SimpleRename]'

